services:

    ntr1_x_default.widget.provider:
        class: NTR1X\LayoutBundle\Widget\WidgetProvider
        arguments: ["@kernel", "NTR1XDefaultBundle", "ntr1xdefault", "widgets.yml"]
        tags:
            - { name: widget.provider }

    ntr1_x_default.component.provider:
        class: NTR1X\LayoutBundle\Component\ComponentProvider
        arguments: ["@kernel", "NTR1XDefaultBundle", "ntr1xdefault", "components.yml"]
        tags:
            - { name: component.provider }
