WidgetMixin:
    tabs:
        -
            name: data
            title: Data
        -
            name: appearance
            title: Appearance
        -
            name: content
            title: Content
    props:
        -
            name: id
            title: 'ID'
            type: 'string'
            placeholder: 'Unique ID'
            tab: 'data'

CollectionMixin:
    props:
        -
            name: path
            title: 'Items'
            type: 'expression'
            placeholder: '$.*'
            tab: data

ContentMixin:
    props:
        -
            name: content
            title: 'Content'
            type: 'rich'
            tab: 'content'

BoxMixin:
    props:
        -
            name: margin
            title: 'Margin'
            type: 'string'
            placeholder: '0px 0px'
            tab: appearance
        -
            name: padding
            title: 'Padding'
            type: 'string'
            placeholder: '0px 0px'
            tab: appearance
        -
            name: innerBorder
            title: 'Inner Border'
            type: 'string'
            placeholder: 'solid 1px #000000'
            tab: appearance
        -
            name: innerBackground
            title: 'Inner Background'
            type: 'string'
            placeholder: '#FFFFFF'
            tab: appearance
        -
            name: innerBackgroundSize
            title: 'Inner Background Size'
            type: 'string'
            placeholder: 'cover'
            tab: appearance
        -
            name: outerBorder
            title: 'Outer Border'
            type: 'string'
            placeholder: 'solid 1px #000000'
            tab: appearance
        -
            name: outerBackground
            title: 'Outer Background'
            type: 'string'
            placeholder: '#FFFFFF'
            tab: appearance
        -
            name: outerBackgroundSize
            title: 'Outer Background Size'
            type: 'string'
            placeholder: 'cover'
            tab: appearance

SizeMixin:
    props:
        -
            name: width
            title: 'Width'
            type: 'string'
            placeholder: '100px'
            tab: appearance
        -
            name: height
            title: 'Height'
            type: 'string'
            placeholder: '100px'
            tab: appearance

Stub:
    title: Stub
    tag: default-stub
    props:
        -
            name: title
            type: 'string'
        -
            name: subtitle
            type: 'string'

Placeholder:
    title: 'Placeholder'
    tag: default-placeholder
    mixins: [ WidgetMixin, BoxMixin, SizeMixin, ContentMixin ]
    thumbnail: 'src/placeholder/placeholder.png'
    categories: [ composite.all, composite.header ]
    params:
        height: { value: 100px }
        content: {value: Placeholder }

Horisontal:
    title: 'Horisontal Stack'
    tag: default-stack-horisontal
    mixins: [ WidgetMixin, BoxMixin ]
    thumbnail: 'src/stack/horisontal.png'
    categories: [ layout.all, layout.stack ]

Vertical:
    title: 'Vertical Stack'
    tag: default-stack-vertical
    mixins: [ WidgetMixin, BoxMixin ]
    thumbnail: 'src/stack/vertical.png'
    categories: [ layout.all, layout.stack ]

Carousel:
    title: 'Carousel'
    tag: default-carousel
    mixins: [ WidgetMixin, BoxMixin, SizeMixin ]
    thumbnail: 'src/carousel/carousel.png'
    categories: [ slider.all ]
    props:
        -
            name: items
            type: multiple
            display: '{{ params.title }}'
            title: Carousel Items
            tab: data
            tabs:
                - { name: data, title: Data }
            props:
                - { name: caption, title: Caption, type: rich, tab: data }
                - { name: background, title: Background, type: string, tab: data }
                - { name: backgroundSize, title: Background Size, type: string, tab: data }
                - { name: url, title: URL, type: string, tab: data }
    params:
        height: { value: '300px' }
        items:
            value:
                -
                    caption: { value: '<h3>First Slide</h3><p>You can change background using settings editor</p>' }
                    background: { value: '#FF3500' }
                    url: { value: null }
                -
                    caption: { value: '<h3>Second Slide</h3><p>You can change background using settings editor</p>' }
                    background: { value: '#DC0055' }
                    url: { value: null }
                -
                    caption: { value: '<h3>Third Slide</h3><p>You can change background using settings editor</p>' }
                    background: { value: '#BF0037' }
                    url: { value: null }

Gallery:
    title: 'Gallery'
    tag: default-gallery
    mixins: [ WidgetMixin, BoxMixin, SizeMixin ]
    thumbnail: 'src/gallery/gallery.png'
    categories: [ slider.all ]
    props:
        - { name: cols, title: Number of Columns, type: string, tab: data }
        - { name: rows, title: Number of Rows, type: string, tab: data }
        - { name: itemWith, title: Item Width, type: string, tab: data }
        - { name: itemHeight, title: Item Height, type: string, tab: data }
        - { name: borderSpacing, title: Border Spacing, type: string, tab: data }
        - { name: borderCollapse, title: Border Collapse, type: string, tab: data }
        -
            name: items
            type: multiple
            display: '{{ params.title }}'
            title: Gallery Items
            tab: data
            tabs:
                - { name: data, title: Data }
            props:
                - { name: caption, title: Caption, type: rich, tab: data }
                - { name: background, title: Background, type: string, tab: data }
                - { name: backgroundSize, title: Background Size, type: string, tab: data }
                - { name: itemBackground, title: Background, type: string, tab: data }
                - { name: itemBackgroundSize, title: Background Size, type: string, tab: data }
                - { name: url, title: URL, type: string, tab: data }
    params:
        cols: { value: 3 }
        rows: { value: 1 }
        borderSpacing: { value: 20px 20px }
        itemHeight: { value: 100px }
        items:
            value:
                -
                    caption: { value: '<h3>First Item</h3><p>You can change item data using settings editor</p>' }
                    itemBackground: { value: '#FF3500' }
                    url: { value: null }
                -
                    caption: { value: '<h3>Second Item</h3><p>You can change item data using settings editor</p>' }
                    itemBackground: { value: '#DC0055' }
                    url: { value: null }
                -
                    caption: { value: '<h3>Third Item</h3><p>You can change item data using settings editor</p>' }
                    itemBackground: { value: '#BF0037' }
                    url: { value: null }
                -
                    caption: { value: '<h3>Fourth Item</h3><p>You can change item data using settings editor</p>' }
                    itemBackground: { value: '#A52939' }
                    url: { value: null }
                -
                    caption: { value: '<h3>Fifth Item</h3><p>You can change item data using settings editor</p>' }
                    itemBackground: { value: '#EE3B80' }
                    url: { value: null }
                -
                    caption: { value: '<h3>Sixth Item</h3><p>You can change item data using settings editor</p>' }
                    itemBackground: { value: '#EE6B9E' }
                    url: { value: null }

NavHorizontal:
    title: 'Navigation Bar'
    tag: default-nav-horisontal
    mixins: [ WidgetMixin, BoxMixin, SizeMixin ]
    thumbnail: 'src/nav/horisontal.png'
    categories: [ navigation.all, navigation.horisontal ]
    props:
        - { name: active, title: Active, type: string, tab: data }
        -
            name: items
            type: multiple
            display: '{{ params.title }}'
            title: Navigation Items
            tab: data
            tabs:
                - { name: data, title: Data }
            props:
                - { name: title, title: Title, type: string, tab: data }
                - { name: url, title: URL, type: string, tab: data }
    params:
        active: { value: home }
        padding: { value: 10px 10px }
        items:
            value:
                -
                    title: { value: Home }
                    value: { value: home }
                    url: { value: null }
                -
                    title: { value: Media }
                    value: { value: media }
                    url: { value: null }
                -
                    title: { value: About }
                    value: { value: about }
                    url: { value: null }

NavVertical:
    title: 'Navigation Stack'
    tag: default-nav-vertical
    mixins: [ WidgetMixin, BoxMixin, SizeMixin ]
    thumbnail: 'src/nav/vertical.png'
    categories: [ navigation.all, navigation.vertical ]
    props:
        - { name: active, title: Active, type: string, tab: data }
        -
            name: items
            type: multiple
            display: '{{ params.title }}'
            title: Navigation Items
            tab: data
            tabs:
                - { name: data, title: Data }
            props:
                - { name: title, title: Title, type: string, tab: data }
                - { name: url, title: URL, type: string, tab: data }
    params:
        active: { value: home }
        padding: { value: 10px 10px }
        items:
            value:
                -
                    title: { value: Home }
                    value: { value: home }
                    url: { value: null }
                -
                    title: { value: Media }
                    value: { value: media }
                    url: { value: null }
                -
                    title: { value: About }
                    value: { value: about }
                    url: { value: null }

InputText:
    title: 'Text'
    tag: default-input-text
    mixins: [ WidgetMixin, BoxMixin, SizeMixin ]
    thumbnail: 'src/input/text.png'
    categories: [ form.all, form.input ]
    props:
        - { name: model, title: Model, type: string, tab: data }
        - { name: type, title: Type, type: string, tab: data }
        - { name: label, title: Label, type: string, tab: data }
        - { name: placeholder, title: Placeholder, type: string, tab: data }
    params:
        margin: { value: '15px 15px' }
        label: { value: 'Email' }
        placeholder: { value: 'user@example.com' }

InputTextarea:
    title: 'Textarea'
    tag: default-input-textarea
    mixins: [ WidgetMixin, BoxMixin, SizeMixin ]
    thumbnail: 'src/input/textarea.png'
    categories: [ form.all, form.input ]
    props:
        - { name: model, title: Model, type: string, tab: data }
        - { name: label, title: Label, type: string, tab: data }
        - { name: placeholder, title: Placeholder, type: string, tab: data }
    params:
        margin: { value: '15px 15px' }
        label: { value: 'Message' }
        placeholder: { value: 'Type message here' }

InputCheckbox:
    title: 'Checkbox'
    tag: default-input-checkbox
    mixins: [ WidgetMixin, BoxMixin ]
    thumbnail: 'src/input/checkbox.png'
    categories: [ form.all, form.input ]
    props:
        - { name: model, title: Model, type: string, tab: data }
        - { name: value, title: Value, type: string, tab: data }
        - { name: checked, title: Checked, type: string, tab: data }
        - { name: label, title: Label, type: string, tab: data }
    params:
        margin: { value: '15px 15px' }
        value: { value: true }
        label: { value: 'I have read and agree to the terms of use' }

InputRadio:
    title: 'Radio'
    tag: default-input-radio
    mixins: [ WidgetMixin, BoxMixin ]
    thumbnail: 'src/input/radio.png'
    categories: [ form.all, form.input ]
    props:
        - { name: checked, title: Checked, type: string, tab: data }
        - { name: value, title: Value, type: string, tab: data }
        - { name: label, title: Label, type: string, tab: data }
        - { name: model, title: Model, type: string, tab: data }
    params:
        margin: { value: '15px 15px' }
        value: { value: true }
        label: { value: 'I have read and agree to the terms of use' }

Rich:
    title: 'Rich'
    tag: default-rich
    mixins: [ WidgetMixin, BoxMixin, ContentMixin ]
    thumbnail: 'rich/rich.png'
    styles: [ 'rich/rich.css' ]
    scripts: [ 'rich/rich.js' ]
    templates: [ 'rich/rich.htm' ]
    categories: [ composite.all ]
    params:
            height: { value: '100px' }
            content: { value: 'Rich' }

Table:
    title: 'Table'
    tag: default-table
    size: { width: 12, height: 5 }
    mixins: [ WidgetMixin, CollectionMixin, BoxMixin ]
    thumbnail: 'table/table.png'
    styles: [ 'table/table.css' ]
    scripts: [ 'table/table.js' ]
    templates: [ 'table/table.htm' ]
    categories: [ composite.all]
    params:
            jsonpath: { value: '{$.competitors.*}' }
    props:
       -
           name: jsonpath
           title: Json Path
           type: string
           tab: data
       -
           name: columns
           type: multiple
           display: '{{ params.title }}'
           title: Columns
           tab: data
           tabs:
               -
                   name: data
                   title: Data
               -
                   name: appearance
                   title: Appearance
               -
                   name: content
                   title: Content
           props:
               -
                   name: title
                   title: Title
                   type: string
                   tab: content
               -
                   name: width
                   title: Width
                   type: string
                   tab: appearance
               -
                   name: type
                   title: Type
                   type: string
                   tab: data
               -
                   name: url
                   title: URL
                   type: string
                   tab: data
               -
                   name: value
                   title: Value
                   type: string
                   tab: data
