WidgetMixin:
    tabs:
        -
            name: data
            title: Data
        -
            name: appearance
            title: Appearance
        -
            name: content
            title: Content
    props:
        -
            name: id
            title: 'ID'
            type: 'string'
            placeholder: 'Unique ID'
            tab: 'data'

SourceMixin:
    props:
        -
            name: source
            title: 'Source'
            type: 'source'
            tab: 'data'

CollectionMixin:
    props:
        -
            name: path
            title: 'Items'
            type: 'expression'
            placeholder: '$.*'
            tab: data

ContentMixin:
    props:
        -
            name: content
            title: 'Content'
            type: 'rich'
            tab: 'content'

BoxMixin:
    props:
        -
            name: margin
            title: 'Margin'
            type: 'string'
            placeholder: '0px 0px'
            tab: appearance
        -
            name: padding
            title: 'Padding'
            type: 'string'
            placeholder: '0px 0px'
            tab: appearance
        -
            name: innerBorder
            title: 'Inner Border'
            type: 'string'
            placeholder: 'solid 1px #000000'
            tab: appearance
        -
            name: innerBackground
            title: 'Inner Background'
            type: 'string'
            placeholder: '#FFFFFF'
            tab: appearance
        -
            name: outerBorder
            title: 'Outer Border'
            type: 'string'
            placeholder: 'solid 1px #000000'
            tab: appearance
        -
            name: outerBackground
            title: 'Outer Background'
            type: 'string'
            placeholder: '#FFFFFF'
            tab: appearance

Header:
    title: 'Header'
    tag: default-header
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'header/header.png'
    styles: [ 'header/header.css' ]
    scripts: [ 'header/header.js' ]
    templates: [ 'header/header.htm' ]
    categories: [ composite.all, composite.header ]
    props:
        -
            name: phone
            title: 'Phone'
            type: 'string'
            placeholder: '8 800 555 35 35'
            tab: content
        -
            name: fill
            title: 'Fill'
            type: 'string'
            placeholder: ''
            tab: appearance
        -
            name: logo
            title: 'Logo'
            type: 'string'
            placeholder: ''
            tab: appearance
Menu:
    title: 'Menu'
    tag: default-menu
    size: { width: 12, height: 1 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'menu/menu.png'
    styles: [ 'menu/menu.css' ]
    scripts: [ 'menu/menu.js' ]
    templates: [ 'menu/menu.htm' ]
    categories: [ composite.all, composite.header ]
    props:
        -
            name: items
            type: multiple
            display: '{{ params.title }}'
            title: Menu Items
            tab: data
            tabs:
                -
                    name: data
                    title: Data
            props:
                -
                    name: title
                    title: Title
                    type: string
                    tab: data
                -
                    name: url
                    title: URL
                    type: string
                    tab: data

Footer:
    title: 'Footer'
    tag: default-footer
    size: { width: 12, height: 1 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'footer/footer.png'
    styles: [ 'footer/footer.css',  'footer/icons.css']
    scripts: [ 'footer/footer.js' ]
    templates: [ 'footer/footer.htm' ]
    categories: [ composite.all, composite.footer ]
    props:
        -
            name: logo
            title: 'Logo Image'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: copyright
            title: 'Copyright'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: contacts
            title: 'Contacts'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: facebook
            title: 'Facebook'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: twitter
            title: 'Twitter'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: google
            title: 'Google'
            type: 'string'
            placeholder: ''
            tab: data

Sitemap:
    title: 'Sitemap'
    tag: default-sitemap
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'sitemap/sitemap.png'
    image: [ ]
    styles: [ ]
    scripts: [ 'sitemap/sitemap.js' ]
    templates: [ 'sitemap/sitemap.htm' ]
    categories: [ composite.all, sitemap.footer ]

2ColumnsLayout:
    title: '2 Columns'
    tag: default-2columns
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'columns/columns-2.png'
    image: [ ]
    styles: [ ]
    scripts: [ ]
    templates: [ ]
    categories: [ layout.all, layout.column ]

Table:
    title: 'Table'
    tag: default-table
    size: { width: 12, height: 5 }
    mixins: [ WidgetMixin, CollectionMixin, BoxMixin, SourceMixin ]
    thumbnail: 'table/table.png'
    styles: [ 'table/table.css' ]
    scripts: [ 'table/table.js' ]
    templates: [ 'table/table.htm' ]
    props:
       -
           name: jsonpath
           title: Json Path
           type: string
           tab: data
       -
           name: columns
           type: multiple
           display: '{{ params.title }}'
           title: Columns
           tab: data
           tabs:
               -
                   name: data
                   title: Data
               -
                   name: appearance
                   title: Appearance
               -
                   name: content
                   title: Content
           props:
               -
                   name: title
                   title: Title
                   type: string
                   tab: content
               -
                   name: width
                   title: Width
                   type: string
                   tab: appearance
               -
                   name: type
                   title: Type
                   type: string
                   tab: data
               -
                   name: url
                   title: URL
                   type: string
                   tab: data
               -
                   name: value
                   title: Value
                   type: string
                   tab: data
