WidgetMixin:
    tabs:
        -
            name: data
            title: Data
        -
            name: appearance
            title: Appearance
        -
            name: content
            title: Content
    props:
        -
            name: id
            title: 'ID'
            type: 'string'
            placeholder: 'Unique ID'
            tab: 'data'

SourceMixin:
    props:
        -
            name: source
            title: 'Source'
            type: 'source'
            tab: 'data'

CollectionMixin:
    props:
        -
            name: path
            title: 'Items'
            type: 'expression'
            placeholder: '$.*'
            tab: data

ContentMixin:
    props:
        -
            name: content
            title: 'Content'
            type: 'rich'
            tab: 'content'

BoxMixin:
    props:
        -
            name: margin
            title: 'Margin'
            type: 'string'
            placeholder: '0px 0px'
            tab: appearance
        -
            name: padding
            title: 'Padding'
            type: 'string'
            placeholder: '0px 0px'
            tab: appearance
        -
            name: innerBorder
            title: 'Inner Border'
            type: 'string'
            placeholder: 'solid 1px #000000'
            tab: appearance
        -
            name: innerBackground
            title: 'Inner Background'
            type: 'string'
            placeholder: '#FFFFFF'
            tab: appearance
        -
            name: outerBorder
            title: 'Outer Border'
            type: 'string'
            placeholder: 'solid 1px #000000'
            tab: appearance
        -
            name: outerBackground
            title: 'Outer Background'
            type: 'string'
            placeholder: '#FFFFFF'
            tab: appearance

Rich:
    title: 'Rich'
    size: { width: 6, height: 5 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin, ContentMixin ]
    styles: [ 'rich/rich.css' ]
    scripts: [ 'rich/rich.js' ]
    templates: [ 'rich/rich.htm' ]

Header:
    title: 'Header'
    size: { width: 12, height: 5 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    styles: [ 'header/header.css' ]
    scripts: [ 'header/header.js' ]
    templates: [ 'header/header.htm' ]

Footer:
    title: 'Footer'
    size: { width: 12, height: 1 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    styles: [ 'footer/footer.css' ]
    scripts: [ 'footer/footer.js' ]
    templates: [ 'footer/footer.htm' ]

Menu:
    title: 'Menu'
    size: { width: 12, height: 1 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    styles: [ 'menu/menu.css' ]
    scripts: [ 'menu/menu.js' ]
    templates: [ 'menu/menu.htm' ]

Table:
    title: 'Table'
    size: { width: 12, height: 5 }
    mixins: [ WidgetMixin, CollectionMixin, BoxMixin, SourceMixin ]
    styles: [ 'table/table.css' ]
    scripts: [ 'table/table.js' ]
    templates: [ 'table/table.htm' ]
    props:
        -
            name: columns
            type: multiple
            display: '{{ params.title }}'
            title: Columns
            tab: data
            tabs:
                -
                    name: data
                    title: Data
                -
                    name: appearance
                    title: Appearance
                -
                    name: content
                    title: Content
            props:
                -
                    name: title
                    title: Title
                    type: string
                    tab: content
                -
                    name: width
                    title: Width
                    type: string
                    tab: appearance
                -
                    name: type
                    title: Type
                    type: string
                    tab: data
                -
                    name: url
                    title: URL
                    type: string
                    tab: data
                -
                    name: value
                    title: Value
                    type: string
                    tab: data
