WidgetMixin:
    tabs:
        -
            name: data
            title: Data
        -
            name: appearance
            title: Appearance
        -
            name: content
            title: Content
    props:
        -
            name: id
            title: 'ID'
            type: 'string'
            placeholder: 'Unique ID'
            tab: 'data'

CollectionMixin:
    props:
        -
            name: path
            title: 'Items'
            type: 'expression'
            placeholder: '$.*'
            tab: data

ContentMixin:
    props:
        -
            name: content
            title: 'Content'
            type: 'rich'
            tab: 'content'

BoxMixin:
    props:
        -
            name: margin
            title: 'Margin'
            type: 'string'
            placeholder: '0px 0px'
            tab: appearance
        -
            name: padding
            title: 'Padding'
            type: 'string'
            placeholder: '0px 0px'
            tab: appearance
        -
            name: innerBorder
            title: 'Inner Border'
            type: 'string'
            placeholder: 'solid 1px #000000'
            tab: appearance
        -
            name: innerBackground
            title: 'Inner Background'
            type: 'string'
            placeholder: '#FFFFFF'
            tab: appearance
        -
            name: outerBorder
            title: 'Outer Border'
            type: 'string'
            placeholder: 'solid 1px #000000'
            tab: appearance
        -
            name: outerBackground
            title: 'Outer Background'
            type: 'string'
            placeholder: '#FFFFFF'
            tab: appearance

SizeMixin:
    props:
        -
            name: width
            title: 'Width'
            type: 'string'
            placeholder: '100px'
            tab: appearance
        -
            name: height
            title: 'Height'
            type: 'string'
            placeholder: '100px'
            tab: appearance

Placeholder:
    title: 'Placeholder'
    tag: default-placeholder
    mixins: [ WidgetMixin, BoxMixin, SizeMixin, ContentMixin ]
    thumbnail: 'src/placeholder/placeholder.png'
    categories: [ composite.all, composite.header ]
    params:
        height: { value: 100px }
        content: {value: Placeholder }


Horisontal:
    title: 'Horisontal Stack'
    tag: default-stack-horisontal
    mixins: [ WidgetMixin, BoxMixin ]
    thumbnail: 'src/stack/horisontal.png'
    categories: [ layout.all, layout.stack ]

Vertical:
    title: 'Vertical Stack'
    tag: default-stack-vertical
    mixins: [ WidgetMixin, BoxMixin ]
    thumbnail: 'src/stack/vertical.png'
    categories: [ layout.all, layout.stack ]

Header:
    title: 'Header'
    tag: default-header
    mixins: [ WidgetMixin, BoxMixin ]
    thumbnail: 'header/header.png'
    styles: [ 'header/header.css' ]
    scripts: [ 'header/header.js' ]
    templates: [ 'header/header.htm' ]
    categories: [ composite.all, composite.header ]
    params:
            phone: { value: '8 800 555 35 35' }
            fill: { value: 'background: url(https://ru.bookagolf.com/bunches/academies/i/23/images/i/36) center right no-repeat; background-size: cover;' }
            logo: { value: 'https://ru.bookagolf.com/bunches/academies/i/23/images/i/28' }
    props:
        -
            name: phone
            title: 'Phone'
            type: 'rich'
            tab: content
        -
            name: fill
            title: 'Fill'
            type: 'string'
            tab: appearance
        -
            name: logo
            title: 'Logo'
            type: 'string'
            tab: appearance

Menu:
    title: 'Menu'
    tag: default-menu
    size: { width: 12, height: 1 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'menu/menu.png'
    styles: [ 'menu/menu.css' ]
    scripts: [ 'menu/menu.js' ]
    templates: [ 'menu/menu.htm' ]
    categories: [ composite.all, composite.header ]
    props:
        -
            name: items
            type: multiple
            display: '{{ params.title }}'
            title: Menu Items
            tab: data
            tabs:
                -
                    name: data
                    title: Data
            props:
                -
                    name: title
                    title: Title
                    type: string
                    tab: data
                -
                    name: url
                    title: URL
                    type: string
                    tab: data

Gallery:
    title: 'Gallery'
    tag: default-gallery
    size: { width: 12, height: 5 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'gallery/gallery.png'
    styles: [ 'gallery/gallery.css' ]
    scripts: [ 'gallery/gallery.js' ]
    templates: [ 'gallery/gallery.htm' ]
    categories: [ composite.all]
    params:
                jsonpath: { value: '$.*' }
                itemUrl: { value: '{$.data.URL}' }
                itemImageUrl: { value: 'i/{$.id}/thumbnail' }
                itemTitle: { value: '{$.data.TITLE}' }
                itemDescription: { value: '{$.data.DESCRIPTION}' }
    props:
       -
           name: jsonpath
           title: Json Path
           type: string
           tab: data
       -
           name: itemUrl
           title: Item URL
           type: string
           tab: data
       -
           name: itemImageUrl
           title: Item Image URL
           type: string
           tab: data
       -
           name: itemTitle
           title: Item Title
           type: string
           tab: data
       -
           name: itemDescription
           title: Item Description
           type: string
           tab: data

Rich:
    title: 'Rich'
    tag: default-rich
    mixins: [ WidgetMixin, BoxMixin, ContentMixin ]
    thumbnail: 'rich/rich.png'
    styles: [ 'rich/rich.css' ]
    scripts: [ 'rich/rich.js' ]
    templates: [ 'rich/rich.htm' ]
    categories: [ composite.all]
    params:
            height: { value: '100px' }
            content: {value: 'Rich' }
Slider:
    title: 'Slider'
    tag: default-slider
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'slider/slider.png'
    styles: [ 'slider/slider.css' ]
    scripts: [ 'slider/slider.js' ]
    templates: [ 'slider/slider.htm' ]
    categories: [ composite.all]

Footer:
    title: 'Footer'
    tag: default-footer
    size: { width: 12, height: 1 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'footer/footer.png'
    styles: [ 'footer/footer.css',  'footer/icons.css']
    scripts: [ 'footer/footer.js' ]
    templates: [ 'footer/footer.htm' ]
    categories: [ composite.all]
    params:
            logo: { value: 'https://ru.bookagolf.com/images/i/4' }
            copyright: { value: 'Все права защищены' }
            contacts: { value: '+7 (495) 410-47-16' }
            facebook: { value: 'https://www.facebook.com/bookagolf' }
            twitter: { value: 'https://twitter.com/bookAgolf' }
            google: { value: 'https://plus.google.com/u/0/communities/102202642996727382512' }
    props:
        -
            name: logo
            title: 'Logo Image'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: copyright
            title: 'Copyright'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: contacts
            title: 'Contacts'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: facebook
            title: 'Facebook'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: twitter
            title: 'Twitter'
            type: 'string'
            placeholder: ''
            tab: data
        -
            name: google
            title: 'Google'
            type: 'string'
            placeholder: ''
            tab: data

Sitemap:
    title: 'Sitemap'
    tag: default-sitemap
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'sitemap/sitemap.png'
    image: [ ]
    styles: [ ]
    scripts: [ 'sitemap/sitemap.js' ]
    templates: [ 'sitemap/sitemap.htm' ]
    categories: [ composite.all]

Table:
    title: 'Table'
    tag: default-table
    size: { width: 12, height: 5 }
    mixins: [ WidgetMixin, CollectionMixin, BoxMixin, SourceMixin ]
    thumbnail: 'table/table.png'
    styles: [ 'table/table.css' ]
    scripts: [ 'table/table.js' ]
    templates: [ 'table/table.htm' ]
    categories: [ composite.all]
    params:
            jsonpath: { value: '{$.competitors.*}' }
    props:
       -
           name: jsonpath
           title: Json Path
           type: string
           tab: data
       -
           name: columns
           type: multiple
           display: '{{ params.title }}'
           title: Columns
           tab: data
           tabs:
               -
                   name: data
                   title: Data
               -
                   name: appearance
                   title: Appearance
               -
                   name: content
                   title: Content
           props:
               -
                   name: title
                   title: Title
                   type: string
                   tab: content
               -
                   name: width
                   title: Width
                   type: string
                   tab: appearance
               -
                   name: type
                   title: Type
                   type: string
                   tab: data
               -
                   name: url
                   title: URL
                   type: string
                   tab: data
               -
                   name: value
                   title: Value
                   type: string
                   tab: data

Items:
    title: 'Items'
    tag: default-items
    size: { width: 12, height: 5 }
    mixins: [ WidgetMixin, BoxMixin, SourceMixin ]
    thumbnail: 'items/items.png'
    styles: [ 'items/items.css' ]
    scripts: [ 'items/items.js' ]
    templates: [ 'items/items.htm' ]
    categories: [ composite.all]
    params:
                jsonpath: { value: '$.*' }
                itemUrl: { value: '{$.data.URL}' }
                itemImageUrl: { value: 'i/{$.id}/thumbnail' }
                itemTitle: { value: '{$.data.TITLE}' }
                itemPromo: { value: '{$.data.PROMO}' }
    props:
       -
           name: jsonpath
           title: Json Path
           type: string
           tab: data
       -
           name: itemUrl
           title: Item URL
           type: string
           tab: data
       -
           name: itemImageUrl
           title: Item Image URL
           type: string
           tab: data
       -
           name: itemTitle
           title: Item Title
           type: string
           tab: data
       -
           name: itemPromo
           title: Item Promo
           type: string
           tab: data