<?php

namespace NTR1X\SearchBundle\Repository;

/**
 * SearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchRepository extends \Doctrine\ORM\EntityRepository
{
}
