<?php

namespace NTR1X\LayoutBundle\Repository;

use NTR1X\LayoutBundle\Entity\Schema;
use NTR1X\LayoutBundle\Entity\Resource;

/**
 * SchemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchemaRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveSchemes($schemes) {

        $em = $this->getEntityManager();
        foreach ($schemes as $data) {
            $this->handleSchema($em, $data);
        }
    }

    private function handleSchema($em, $data) {

        if (isset($data['_action'])) {

            switch ($data['_action']) {
                case 'remove':
                    $this->handleSchemaRemove($em, $data);
                    break;
                case 'update':
                    $schema = $this->handleSchemaUpdate($em, $data);
                    $this->handleSchemaTree($em, $schema, $data);
                    break;
                case 'create':
                    $schema = $this->handleSchemaCreate($em, $data);
                    $this->handleSchemaTree($em, $schema, $data);
                    break;
            }

        } else {
            $schema = $this->findOneById($data['id']);
            $this->handleSchemaTree($em, $schema, $data);
        }
    }

    private function handleSchemaCreate($em, $data) {

        $schema = (new Schema())
            ->setName($data['name'])
            ->setUrl($data['url'])
            ->setResource(new Resource())
        ;

        $em->persist($schema);
        $em->flush();

        $resource = $schema->getResource();

        $resource
            ->setName("/schemes/{$schema->getId()}")
            ->setParams($this->clearParams($data['resource']['params']))
        ;

        $em->persist($resource);
        $em->flush();

        return $schema;
    }

    private function handleSchemaUpdate($em, $data) {

        $schema = $this->findOneById($data['id'])
            ->setName($data['name'])
            ->setUrl($data['url'])
        ;

        $resource = $schema->getResource();

        $resource
            ->setParams($this->clearParams($data['resource']['params']))
        ;

        $em->persist($schema);
        $em->flush();

        return $schema;
    }

    private function handleSchemaRemove($em, $data) {

        $schema = $this->findOneById($data['id']);

        $em->remove($schema);
        $em->flush();
    }

    private function handleSchemaTree($em, $data) {
    }

    private function clearParams($data) {

        $array = [];

        foreach ($data as $param) {
            if (!isset($param['_action']) || $param['_action'] != 'remove') {
                $p = $param;
                unset($p['_action']);
                $array[] = $p;
            }
        }

        return $array;
    }
}
