security:
    resource:   "@AppBundle/Controller/SecurityController.php"
    type:       annotation
    prefix:     /

portals:
    resource:   "@AppBundle/Controller/PortalsController.php"
    type:       annotation
    prefix:     /

default:
    resource:   "@AppBundle/Controller/DefaultController.php"
    type:       annotation
    prefix:     /
