<?php

namespace NTR1X\UploadBundle\Repository;

/**
 * UploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadRepository extends \Doctrine\ORM\EntityRepository
{
}
