-
    name: composite
    title: Composites
    items:
        - { name: all, title: All Items }
        - { name: header, title: Headers }
        - { name: footer, title: Footers }
-
    name: navigation
    title: Navigation
    items:
        - { name: all, title: All Items }
        - { name: vertical, title: Vertical }
        - { name: horisontal, title: Horisontal }
-
    name: slider
    title: Slider
    items:
        - { name: all, title: All Items }
-
    name: layout
    title: Layouts
    items:
        - { name: all, title: All Items }
        - { name: stack, title: Stack }
-
    name: form
    title: Forms
    items:
        - { name: all, title: All Items }
        - { name: button, title: Buttons }
        - { name: input, title: Inputs }
-
    name: text
    title: Text Blocks
    items:
        - { name: all, title: All Items }
