-
    name: composites
    title: Composite Elements
    items:
        - { name: header, title: Headers }
        - { name: footer, title: Footers }
        - { name: navigation, title: Navigation }
        - { name: slider, title: Slider }
        - { name: text, title: Text }
        - { name: other, title: Other }

-
    name: forms
    title: Form Elements
    items:
        - { name: input, title: Inputs }
        - { name: button, title: Buttons }

-
    name: layouts
    title: Container Elements
    items:
        - { name: stack, title: Stack }

-
    name: icons
    title: Free Icons
    items:
        - { name: social, title: Social }
        - { name: action, title: Actions }

-
    name: images
    title: Free Images
    items:
        - { name: abstract, title: Abstract }
        - { name: nature, title: Nature }
