bindings:
    scripts:
        - 'src/bindings/bindings.js'
    templates:
        - 'src/bindings/bindings-dialog.htm'

schemes:
    scripts:
        - 'src/schemes/schemes.js'
    templates:
        - 'src/schemes/schemes.htm'
        - 'src/schemes/schemes-list.htm'
        - 'src/schemes/schemes-dialog.htm'
        - 'src/schemes/schemes-settings.htm'
        - 'src/schemes/schemes-settings-list.htm'
        - 'src/schemes/schemes-settings-dialog.htm'

domains:
    scripts:
        - 'src/domains/domains.js'
    templates:
        - 'src/domains/domains.htm'
        - 'src/domains/domains-list.htm'
        - 'src/domains/domains-dialog.htm'
        - 'src/domains/domains-settings.htm'
        - 'src/domains/domains-settings-list.htm'
        - 'src/domains/domains-settings-dialog.htm'

pages:
    scripts:
        - 'src/pages/pages.js'
        - 'src/pages/sources/sources.js'
        - 'src/pages/widgets/widgets.js'
        - 'src/pages/widgets/params/params.js'
    templates:
        - 'src/pages/pages.htm'
        - 'src/pages/pages-list.htm'
        - 'src/pages/pages-dialog.htm'

        - 'src/pages/pages-settings.htm'
        - 'src/pages/pages-settings-list.htm'
        - 'src/pages/pages-settings-dialog.htm'

        - 'src/pages/pages-metas.htm'
        - 'src/pages/pages-metas-list.htm'
        - 'src/pages/pages-metas-dialog.htm'

        - 'src/pages/sources/sources.htm'
        - 'src/pages/sources/sources-list.htm'
        - 'src/pages/sources/sources-dialog.htm'
        - 'src/pages/sources/sources-params.htm'
        - 'src/pages/sources/sources-params-list.htm'
        - 'src/pages/sources/sources-params-dialog.htm'

        - 'src/pages/widgets/widgets.htm'
        - 'src/pages/widgets/widgets-list.htm'
        - 'src/pages/widgets/widgets-dialog.htm'

        - 'src/pages/widgets/params/params.htm'
        - 'src/pages/widgets/params/params-list.htm'
        - 'src/pages/widgets/params/params-string.htm'
        - 'src/pages/widgets/params/params-rich.htm'
        - 'src/pages/widgets/params/params-source.htm'
        - 'src/pages/widgets/params/params-multiple.htm'
        - 'src/pages/widgets/params/params-multiple-editor.htm'
        - 'src/pages/widgets/params/params-multiple-dialog.htm'
        - 'src/pages/widgets/params/params-multiple-list.htm'

widgets:
    scripts:
        - 'src/widgets/widgets.js'
    templates:
        - 'src/widgets/widgets.htm'
        - 'src/widgets/widgets-list.htm'
        - 'src/widgets/widgets-dialog.htm'

settings:
    scripts:
        - 'src/settings/settings.js'
    templates:
        - 'src/settings/settings-dialog.htm'

shell:
    scripts:
        - 'src/shell/palette/palette.js'
    styles:
        - 'src/shell/shell.css'
        - 'src/shell/palette/palette.css'
    templates:
        - 'src/shell/palette/palette.htm'
