bindings:
    scripts:
        - 'bindings/bindings.js'
    templates:
        - 'bindings/bindings-dialog.htm'

schemes:
    scripts:
        - 'schemes/schemes.js'
    templates:
        - 'schemes/schemes.htm'
        - 'schemes/schemes-list.htm'
        - 'schemes/schemes-dialog.htm'
        - 'schemes/schemes-settings.htm'
        - 'schemes/schemes-settings-list.htm'
        - 'schemes/schemes-settings-dialog.htm'

domains:
    scripts:
        - 'domains/domains.js'
    templates:
        - 'domains/domains.htm'
        - 'domains/domains-list.htm'
        - 'domains/domains-dialog.htm'
        - 'domains/domains-settings.htm'
        - 'domains/domains-settings-list.htm'
        - 'domains/domains-settings-dialog.htm'

pages:
    scripts:
        - 'pages/pages.js'
        - 'pages/sources/sources.js'
        - 'pages/widgets/widgets.js'
        - 'pages/widgets/params/params.js'
    templates:
        - 'pages/pages.htm'
        - 'pages/pages-list.htm'
        - 'pages/pages-dialog.htm'

        - 'pages/pages-settings.htm'
        - 'pages/pages-settings-list.htm'
        - 'pages/pages-settings-dialog.htm'

        - 'pages/pages-metas.htm'
        - 'pages/pages-metas-list.htm'
        - 'pages/pages-metas-dialog.htm'

        - 'pages/sources/sources.htm'
        - 'pages/sources/sources-list.htm'
        - 'pages/sources/sources-dialog.htm'
        - 'pages/sources/sources-params.htm'
        - 'pages/sources/sources-params-list.htm'
        - 'pages/sources/sources-params-dialog.htm'

        - 'pages/widgets/widgets.htm'
        - 'pages/widgets/widgets-list.htm'
        - 'pages/widgets/widgets-dialog.htm'

        - 'pages/widgets/params/params.htm'
        - 'pages/widgets/params/params-list.htm'
        - 'pages/widgets/params/params-string.htm'
        - 'pages/widgets/params/params-rich.htm'
        - 'pages/widgets/params/params-source.htm'
        - 'pages/widgets/params/params-multiple.htm'
        - 'pages/widgets/params/params-multiple-editor.htm'
        - 'pages/widgets/params/params-multiple-dialog.htm'
        - 'pages/widgets/params/params-multiple-list.htm'

widgets:
    scripts:
        - 'widgets/widgets.js'
    templates:
        - 'widgets/widgets.htm'
        - 'widgets/widgets-list.htm'
        - 'widgets/widgets-dialog.htm'

settings:
    scripts:
        - 'settings/settings.js'
    templates:
        - 'settings/settings-dialog.htm'
