<?php

namespace NTR1X\ApplyBundle\Repository;

/**
 * ApplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplyRepository extends \Doctrine\ORM\EntityRepository
{
}
